### ISSUE TITLE
--message not working with space

### ISSUE THREAD

**Issue by esby** [iliana/mw#12]
Not sure if it is an issue, but i had to use _ instead of ' ' (space) in my message to have  

> mw commit -m "some text" 

works correctly: it was thinking the rest of the message commit were files to check and it was not commiting anything.

**Comment by reagle** [comment]
I'm not sure I understand, but this sounds like a shell issue. That is, naked spaces on the command line can cause problems and so you need to protect them with spaces.

**Comment by esby** [comment]
protect them with spaces? you mean single quotes (') or backslash -() ?

**Comment by reagle** [comment]
On 06/19/2012 10:21 AM, yves tennevin wrote:

> protect them with spaces? you mean single quotes (') or backslash -() ?

That can depend on the shell (e.g., bash) that you type it into.

**Comment by esby** [comment]
I think the problem was linked to the fact i was using an old version of mw. 
I am not sure, because I reinstalled my box with debian instead of the ubuntu server version I was using just today.
(the box was using set up with bash for both cases)

I installed the needed dependencies for mw and it is working fine in my sample test.
