### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by avindra** [iliana/mw#18]
Seems to be broken  as of 3/12/2018:

```
$ mw init https://commons.wikimedia.org/w/api.php
$ mw login
Username: avindra
Password: 
Login with token
Login failed: Failed
```

**Comment by avindra** [comment]
NVM, I used the wrong username :upside_down_face:

**Comment by reagle** [comment]
Does that means it's working? If so, I'm pleasantly surprised, nobody has touched it since 2012! (I now use [Mediawiker](https://github.com/tosher/Mediawiker) in Sublime Text).

**Comment by avindra** [comment]
@reagle  Definitely working. I've used to edit a few hundred files already.
