### ISSUE TITLE
issue with accentued characters

### ISSUE THREAD

**Issue by esby** [iliana/mw#2]
Retrieving normal pages works, but when pages are using accentued characters or special non standard caracters, their retrieving works, but they can't be diffed or commited back.

one example with 
http://commons.wikimedia.org/wiki/File:Luc_Lef%C3%A8bvre_%28Ptitluc%29_05.jpg
( api_url = http://commons.wikimedia.org/w/api.php )

The file description is correctly retrieved.

657 2010-05-15 00:35 File:Luc_Lefèbvre_(Ptitluc)_05.jpg.wiki

But pull / status / commit will not work:

Error for status command:

(...)/src/mw/metadir.py:93: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if pagename in pagedict.keys():

**Comment by iliana** [comment]
can I please get a full traceback on all there of those commands?

**Comment by esby** [comment]
short question what do you call a 'full traceback' 
Is it just the full console output of the tool or something else? (using strace for example?)

**Comment by iliana** [comment]
just all of the console output, including your interaction with the program

**Comment by esby** [comment]
http://www.pastebin.org/237902

./mw pull "File:Luc Lefèbvre (Ptitluc) 06.jpg"

$ ./mw st

<snipped>/mw/src/mw/metadir.py:93: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if pagename in pagedict.keys():

? File:Luc_Lefèbvre_(Ptitluc)_05.jpg.wiki

? File:Luc_Lefèbvre_(Ptitluc)_06.jpg.wiki

$ ./mw diff

<snipped>/mw/src/mw/metadir.py:93: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if pagename in pagedict.keys():

$ ./mw ci

<snipped>/mw/src/mw/metadir.py:93: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if pagename in pagedict.keys():

? File:Luc_Lefèbvre_(Ptitluc)_05.jpg.wiki

? File:Luc_Lefèbvre_(Ptitluc)_06.jpg.wiki

nothing to commit

**Comment by esby** [comment]
patch sent to you

**Comment by iliana** [comment]
fixed in 731ebcb5bb71d65d81065a34caa627081b5e0731
