### ISSUE TITLE
issue when blanking page

### ISSUE THREAD

**Issue by esby** [iliana/mw#3]
If you blank a page the tool will crash.

There are comparaison to text checking for linefeed

if text[-1] == '\n':

those crashes when text is empty:

suggested fix:

replace
  if text[-1] == '\n':

by
  if (len(text)!=0) and (text[-1] == '\n'):

Now maybe there is a better way of doing that.
This should be done each time something is compared to '\n' anyway.

**Comment by esby** [comment]
patch sent to you

**Comment by iliana** [comment]
patch merged. (d5e0d569024805e42039955f2e38024fcfdb0f7b)
