### ISSUE TITLE
Impossible to commit while the only modification was adding a terminal linefeed 

### ISSUE THREAD

**Issue by esby** [iliana/mw#4]
If the only change to a page is a terminal linefeed:

 'mw diff' will detect the difference.

 but it is impossible to make the commit.

I'll submit a patch to fix this issue (the file will be skipped.)

**Comment by iliana** [comment]
sounds great.

**Comment by esby** [comment]
this is coming from mediawiki stripping the last line feed if this is present.
I fixed the issue of commiting, now I am wondering if this is the tool job to clean the file.

**Comment by esby** [comment]
patch sent to you

**Comment by iliana** [comment]
patch merged (d5e0d569024805e42039955f2e38024fcfdb0f7b)
