### ISSUE TITLE
Feature suggestion - Retrieving page in a given category

### ISSUE THREAD

**Issue by esby** [iliana/mw#5]
I have been thinking to a feature that would fetch a category page and possibly allowing to fetch all pages that are categorized to this page.

Maybe there is no need to retrieve the category in itself, since it's just some extra metadata, but it should be possible to retrieve the page that belongs to it via the api.

The same could be done for template inclusion.

**Comment by iliana** [comment]
just noticed you wrote this (at the same time I started hacking on this again, oddly enough!) and merged into my branch

merged in 0ed615781d6e53236fe84cc5c9896956dea5a067

**Comment by esby** [comment]
good.
